### ISSUE TITLE
High load on high-performance computing cluster

### ISSUE THREAD

**Issue by benfarmer05** [ryanbooker/framer#10]
Hi there - I am new to GitHub and shell scripting so I hope you can bear with me! Thank you for providing this great program for pulling frames from videos. I am using it for coral colony photogrammetry. I was able to get this script running on ~2 minute videos using my personal Mac (Macbook Pro M1 Silicon), albeit with the fan really kicking into high gear. When I tried to run this on my university's high-performance computing cluster, I ran into issues. Running on one node (with one processor) seems to work okay, however when I allow all 20 available processors on a node to take on the job, the load increases immensely and eventually the node goes offline (without any frames being exported). Am I missing something important about preparing the script for parallelization? It might have to do with GNU Parallel.

Thank you!

**Comment by ryanbooker** [comment]
Sorry I have only just seen this message!

I'm not really sure how the clusters will work. This tool uses a program called GNU parallel to parallelise the frame filtering. parallel will eat up all the threads it can find and saturate the system to process as fast as it can.

I will add a parameter to allow setting the maximum number of threads and default it to something sane.

I hope you still find the tool useful. It was a neat little idea I had for doing coral photogrammetry with go pro footage.

**Comment by ryanbooker** [comment]
There is now a `-j` option for specifying GNU parallel's job count. This can take a % of cores, or integer job count. 
e.g. 
```
-j 20% # consume 20% of cores
-j 10 # allow 10 parallel jobs
-j 0 # eat all eh resources of your computer to process everything as fast as possible
```

**Comment by benfarmer05** [comment]
Thank you!! We ended up using this script quite a lot, if I remember
correctly. We chose to use it on one high-end machine, but it is good to
know we may be able to try this on a cluster again in the future.
